language: clojure
lein: lein2
before_install:
  - sudo add-apt-repository -y ppa:wnoronha/thrift
  - sudo apt-get update -qq
  - sudo apt-get install -qq thrift-compiler
  - which thrift
before_script: lein2 all deps
script: lein2 all test
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
